### ISSUE TITLE
Getting an error while running the python file

### ISSUE THREAD

**Issue by chetan-atmecs** [myscale/myscale_callback#10]
if retried else DatabaseError(err_str) from None
clickhouse_connect.driver.exceptions.DatabaseError: HTTPDriver for http://localhost:8123 returned response code 500)
 std::exception. Code: 1001, type: SearchIndexException, e.what() = Error(BAD_ARGUMENTS): Unknown index type for Float32 Vector: MSTG (version 23.3.2.1)

**Comment by lqhl** [comment]
@xujryan

**Comment by xujryan** [comment]
The error arises because the open-source version of MyScaleDB does not support the MSTG index. You need to set `index_type="SCANN"` in your configuration.

Here is an example of how to set it up:
```
from langchain_community.vectorstores import MyScale, MyScaleSettings

vectorstore = MyScale.from_texts(["xxx"], embedding=OpenAIEmbeddings(), config=MyScaleSettings(index_type="SCANN"))
```

Alternatively, you can try using [MyScale Cloud](https://myscale.com/) to utilize the MSTG index, which offers better performance compared to SCANN.
